export const GET_DEPARTEMENT = 'GET_DEPARTEMENT';
export const GET_DEPARTEMENT_PENDING = 'GET_DEPARTEMENT_PENDING';
export const GET_DEPARTEMENT_SUCCESS = 'GET_DEPARTEMENT_SUCCESS';
export const GET_DEPARTEMENT_ERROR = 'GET_DEPARTEMENT_ERROR';
export const GET_DEPARTEMENT_BY_ID = 'GET_DEPARTEMENT_BY_ID';
