export const GET_CATEGORIE = 'GET_CATEGORIE';
export const GET_CATEGORIE_PENDING = 'GET_CATEGORIE_PENDING';
export const GET_CATEGORIE_SUCCESS = 'GET_CATEGORIE_SUCCESS';
export const GET_CATEGORIE_ERROR = 'GET_CATEGORIE_ERROR';
