export const GET_USERDETAIL = 'GET_USERDETAIL';

export const GET_USERDETAIL_PENDING = 'GET_USERDETAIL_PENDING';
export const GET_USERDETAIL_SUCCESS = 'GET_USERDETAIL_SUCCESS';
export const GET_USERDETAIL_ERROR = 'GET_USERDETAIL_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER'; 

export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export const RECOVER_PASSWORD_ERROR = 'RECOVER_PASSWORD_ERROR';
