export const GET_USERDETAIL = 'GET_USERDETAIL';

export const GET_USERDETAIL_PENDING = 'GET_USERDETAIL_PENDING';
export const GET_USERDETAIL_SUCCESS = 'GET_USERDETAIL_SUCCESS';
export const GET_USERDETAIL_ERROR = 'GET_USERDETAIL_ERROR';

export const LOGOUT_USER = 'LOGOUT_USER'; 
export const LOGIN_USER = 'LOGIN_USER'; 
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'; 
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'; 

export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const RECOVER_PASSWORD_SUCCESS = 'RECOVER_PASSWORD_SUCCESS';
export const RECOVER_PASSWORD_ERROR = 'RECOVER_PASSWORD_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';


export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REGISTER_USER_EMPTY_MESSAGE = 'REGISTER_USER_EMPTY_MESSAGE';


