export const GET_MYANNONCE = 'GET_MYANNONCE';
export const GET_MYANNONCE_PENDING = 'GET_MYANNONCE_PENDING';
export const GET_MYANNONCE_SUCCESS = 'GET_MYANNONCE_SUCCESS';
export const GET_MYANNONCE_ERROR = 'GET_MYANNONCE_ERROR';

export const SEARCH_ANNONCE = 'SEARCH_ANNONCE';
export const SEARCH_ANNONCE_SUCCESS = 'SEARCH_ANNONCE_SUCCESS';
export const SEARCH_ANNONCE_ERROR = 'SEARCH_ANNONCE_ERROR';

export const GET_ANNONCE_BY_ID = 'GET_ANNONCE_BY_ID';
export const GET_ANNONCE_BY_ID_SUCCESS = 'GET_ANNONCE_BY_ID_SUCCESS';
export const GET_ANNONCE_BY_ID_ERROR = 'GET_ANNONCE_BY_ID_ERROR';

export const GET_ANNONCE_QUESTION = 'GET_ANNONCE_QUESTION';
export const GET_ANNONCE_QUESTION_SUCCESS = 'GET_ANNONCE_QUESTION_SUCCESS';
export const GET_ANNONCE_QUESTION_ERROR = 'GET_ANNONCE_QUESTION_ERROR';