export const GET_REGION = 'GET_REGION';
export const GET_REGION_PENDING = 'GET_REGION_PENDING';
export const GET_REGION_SUCCESS = 'GET_REGION_SUCCESS';
export const GET_REGION_ERROR = 'GET_REGION_ERROR';
