export const CONTACT_SELLER = 'CONTACT_SELLER';

export const CONTACT_SELLER_PENDING = 'CONTACT_SELLER_PENDING';
export const CONTACT_SELLER_SUCCESS = 'CONTACT_SELLER_SUCCESS';
export const CONTACT_SELLER_ERROR = 'CONTACT_SELLER_ERROR';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';