export const SEND_QUESTION_SUCCESS = 'SEND_QUESTION_SUCCESS';
export const SEND_QUESTION_ERROR = 'SEND_QUESTION_ERROR';
export const SEND_QUESTION = 'SEND_QUESTION';


export const SEND_REPLY_SUCCESS = 'SEND_REPLY_SUCCESS';
export const SEND_REPLY_ERROR = 'SEND_REPLY_ERROR';
export const SEND_REPLY = 'SEND_REPLY';